title: Redes (TA048)
description: "Apuntes del libro 'Computer Networking - A Top Down Approach'"

remote_theme: just-the-docs/just-the-docs

button:
  text: "Descargar en PDF"
  href: "?print-pdf"

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

search_enabled: true
