title: FIUBA
favicon_ico: "/assets/favicon.ico"

remote_theme: just-the-docs/just-the-docs
color_scheme: dark

button:
  text: "Descargar en PDF"
  href: "?print-pdf"

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

search_enabled: true

aux_links:
  "Ver en GitHub":
    - "https://github.com/flopeztancredi/flopeztancredi.github.io"

aux_links_new_tab: false

just_the_docs:
  collections:
    docs:
      nav_exclude: false
      nav_order:
        - Redes
        - EBT1